services:
  vaas-mcp:
    container_name: vaas-mcp
    build:
      context: ./vaas-mcp
    ports:
      - "9090:9090"
    env_file:
      - ./vaas-mcp/.env
    networks:
      - agent-network
    environment:
      - HF_HOME=/root/.cache/huggingface
    volumes:
      - ./.vscode:/app/.vscode
      - shared_media:/app/shared_media
      - ~/.cache:/root/.cache
      - ~/.cache/huggingface:/root/.cache/huggingface
    
    deploy:
      resources:
        limits:
          cpus: '4' 
          memory: 4G   
        reservations:
          cpus: '4'    
          memory: 4G   

  vaas-api:
    container_name: vaas-api
    build:
      context: ./vaas-api
    ports:
      - "8080:8080"
    environment:
      - DISABLE_NEST_ASYNCIO=True
    env_file:
      - ./vaas-api/.env
    networks:
      - agent-network
    depends_on:
      - vaas-mcp
    volumes:
      - shared_media:/app/shared_media
      - ./.vscode:/app/.vscode
  vaas-ui:
    container_name: vaas-ui
    build:
      context: ./vaas-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - vaas-api
      - vaas-mcp
    networks:
      - agent-network
    volumes:
      - shared_media:/app/shared_media

networks:
  agent-network:
    name: agent-network

volumes:
  shared_media:
    name: shared_media